-- migrate:up
INSERT INTO provincias (nombre, departamento_id) VALUES ('Chachapoyas', 1);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Bagua', 1);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Bongará', 1);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Condorcanqui', 1);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Luya', 1);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Rodríguez de Mendoza', 1);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Utcubamba', 1);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Huaraz', 2);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Aija', 2);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Antonio Raymondi', 2);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Asunción', 2);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Bolognesi', 2);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Carhuaz', 2);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Carlos Fermín Fitzcarrald', 2);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Casma', 2);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Corongo', 2);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Huari', 2);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Huarmey', 2);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Mariscal Luzuriaga', 2);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Ocros', 2);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Pallasca', 2);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Recuay', 2);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Santa', 2);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Sihuas', 2);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Yungay', 2);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Abancay', 3);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Andahuaylas', 3);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Antabamba', 3);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Aymaraes', 3);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Cotabambas', 3);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Chincheros', 3);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Grau', 3);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Arequipa', 4);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Camaná', 4);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Caravelí', 4);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Castilla', 4);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Caylloma', 4);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Condesuyos', 4);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Islay', 4);
INSERT INTO provincias (nombre, departamento_id) VALUES ('La Unión', 4);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Huamanga', 5);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Cangallo', 5);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Huanca Sancos', 5);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Huanta', 5);
INSERT INTO provincias (nombre, departamento_id) VALUES ('La Mar', 5);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Lucanas', 5);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Parinacochas', 5);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Páucar del Sara Sara', 5);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Sucre', 5);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Vilcashuamán', 5);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Cajamarca', 6);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Celendín', 6);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Chota', 6);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Contumazá', 6);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Cutervo', 6);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Hualgayoc', 6);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Jaén', 6);
INSERT INTO provincias (nombre, departamento_id) VALUES ('San Ignacio', 6);
INSERT INTO provincias (nombre, departamento_id) VALUES ('San Marcos', 6);
INSERT INTO provincias (nombre, departamento_id) VALUES ('San Miguel', 6);
INSERT INTO provincias (nombre, departamento_id) VALUES ('San Pablo', 6);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Santa Cruz', 6);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Callao', 7);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Cusco', 8);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Acomayo', 8);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Anta', 8);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Calca', 8);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Canchis', 8);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Chumbivilcas', 8);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Espinar', 8);
INSERT INTO provincias (nombre, departamento_id) VALUES ('La Convención', 8);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Paruro', 8);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Paucartambo', 8);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Quispicanchi', 8);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Urubamba', 8);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Huancavelica', 9);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Acobamba', 9);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Angaraes', 9);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Castrovirreyna', 9);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Churcampa', 9);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Huaytará', 9);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Tayacaja', 9);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Huánuco', 10);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Ambo', 10);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Dos de Mayo', 10);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Huacaybamba', 10);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Huánuco', 10);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Leoncio Prado', 10);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Marañón', 10);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Pachitea', 10);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Puños', 10);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Yarowilca', 10);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Ica', 11);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Chincha', 11);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Nazca', 11);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Palpa', 11);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Pisco', 11);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Mazamari', 12);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Pichanaki', 12);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Satipo', 12);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Chanchamayo', 12);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Chupaca', 12);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Concepción', 12);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Junín', 12);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Satipo', 12);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Tarma', 12);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Yauli', 12);
INSERT INTO provincias (nombre, departamento_id) VALUES ('La Libertad', 13);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Ascope', 13);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Bolívar', 13);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Cajamarca', 13);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Chepén', 13);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Gran Chimu', 13);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Julcán', 13);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Otuzco', 13);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Pacasmayo', 13);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Pataz', 13);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Santiago de Chuco', 13);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Trujillo', 13);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Lambayeque', 14);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Chiclayo', 14);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Ferreñafe', 14);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Lambayeque', 14);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Lima', 15);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Barranca', 15);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Cajatambo', 15);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Canta', 15);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Cañete', 15);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Huaral', 15);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Huarochirí', 15);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Lima', 15);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Oyon', 15);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Yauyos', 15);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Loreto', 16);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Alto Nanay', 16);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Datem del Marañón', 16);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Loreto', 16);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Maynas', 16);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Requena', 16);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Ucayali', 16);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Madre de Dios', 17);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Manu', 17);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Tambopata', 17);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Tahuamanu', 17);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Moquegua', 18);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Mariscal Nieto', 18);
INSERT INTO provincias (nombre, departamento_id) VALUES ('General Sánchez Cerro', 18);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Ilo', 18);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Pasco', 19);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Daniel Alcides Carrión', 19);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Oxapampa', 19);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Piura', 20);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Ayabaca', 20);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Huancabamba', 20);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Morropón', 20);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Paita', 20);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Piura', 20);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Sechura', 20);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Puno', 21);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Azángaro', 21);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Carabaya', 21);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Chucuito', 21);
INSERT INTO provincias (nombre, departamento_id) VALUES ('El Collao', 21);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Huancané', 21);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Lampa', 21);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Melgar', 21);
INSERT INTO provincias (nombre, departamento_id) VALUES ('San Antonio de Putina', 21);
INSERT INTO provincias (nombre, departamento_id) VALUES ('San Román', 21);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Sandia', 21);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Yunguyo', 21);
INSERT INTO provincias (nombre, departamento_id) VALUES ('San Martín', 22);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Bellavista', 22);
INSERT INTO provincias (nombre, departamento_id) VALUES ('El Dorado', 22);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Huallaga', 22);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Lamas', 22);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Mariscal Cáceres', 22);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Picota', 22);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Rioja', 22);
INSERT INTO provincias (nombre, departamento_id) VALUES ('San Martín', 22);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Tocache', 22);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Tacna', 23);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Tacna', 23);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Candarave', 23);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Jorge Basadre', 23);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Tumbes', 24);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Contralmirante Villar', 24);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Tumbes', 24);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Ucayali', 25);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Atalaya', 25);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Coronel Portillo', 25);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Padre Abad', 25);
INSERT INTO provincias (nombre, departamento_id) VALUES ('Purús', 25);

-- migrate:down
DELETE FROM provincias;
