-- migrate:up
INSERT INTO distritos (id, nombre, provincia_id) VALUES (1, 'Miraflores', 124);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (2, 'San Isidro', 124);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (3, 'Barranco', 124);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (4, 'San Borja', 124);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (5, 'Lima Cercado', 124);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (6, 'Arequipa', 33);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (7, 'Cayma', 33);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (8, 'Yanahuara', 33);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (9, 'José Luis Bustamante y Rivero', 33);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (10, 'Santiago de Arequipa', 33);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (11, 'Cusco', 64);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (12, 'San Sebastián', 64);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (13, 'San Jerónimo', 64);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (14, 'Santiago', 64);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (15, 'Wanchaq', 64);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (16, 'Piura', 152);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (17, 'Castilla', 152);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (18, 'Veintiséis de Octubre', 152);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (19, 'Sechura', 152);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (20, 'Sullana', 152);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (21, 'Trujillo', 108);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (22, 'El Porvenir', 108);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (23, 'La Esperanza', 108);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (24, 'Víctor Larco Herrera', 108);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (25, 'Moche', 108);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (26, 'Huancayo', 104);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (27, 'El Tambo', 104);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (28, 'Chupaca', 104);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (29, 'Concepción', 104);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (30, 'Jauja', 104);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (31, 'Iquitos', 134);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (32, 'Belén', 134);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (33, 'Punchana', 134);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (34, 'Nauta', 134);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (35, 'Requena', 134);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (36, 'Moyobamba', 171);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (37, 'Tarapoto', 171);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (38, 'Juanjuí', 171);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (39, 'Picota', 171);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (40, 'Huallaga', 171);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (41, 'Huaraz', 8);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (42, 'Chimbote', 8);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (43, 'Caraz', 8);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (44, 'Santa', 8);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (45, 'Bolognesi', 8);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (46, 'Tacna', 181);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (47, 'Coronel Gregorio Albarracín Lanchipa', 181);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (48, 'Ciudad Nueva', 181);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (49, 'Alto de la Alianza', 181);
INSERT INTO distritos (id, nombre, provincia_id) VALUES (50, 'Pocollay', 181);

-- migrate:down
DELETE FROM distritos;
